# Generated by Django 4.1.3 on 2023-05-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
                ('file', models.ImageField(default='default.jpg', upload_to='files/')),
                ('api_type', models.CharField(choices=[('REST', 'REST API'), ('FAST', 'FAST API')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='files/')),
                ('file', models.FileField(upload_to='files/')),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Script_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
                ('file', models.ImageField(default='default.jpg', upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Web_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
