# Generated by Django 4.1.3 on 2023-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='files/')),
                ('fm_type', models.CharField(choices=[('DJANGO', 'DANGO FM'), ('FLASK', 'FLASK FM'), ('NODE.JS', 'NODE FM')], max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Web_file',
        ),
        migrations.RemoveField(
            model_name='api',
            name='file',
        ),
        migrations.RemoveField(
            model_name='api',
            name='video',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='file',
        ),
        migrations.RemoveField(
            model_name='script_projects',
            name='file',
        ),
        migrations.AddField(
            model_name='api',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='script_projects',
            name='github_link',
            field=models.CharField(default='', max_length=400),
        ),
    ]
