# Generated by Django 4.1.3 on 2023-05-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_website_delete_web_file_remove_api_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
