# Generated by Django 4.1.3 on 2023-06-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_message_name_alter_message_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_type',
            field=models.CharField(choices=[('DRF', 'REST API'), ('FAST', 'FAST API')], max_length=4),
        ),
    ]
