# Generated by Django 4.1.3 on 2023-06-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_api_api_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_type',
            field=models.CharField(choices=[('DRF', 'DJANGO REST API'), ('FAST', 'FAST API')], max_length=4),
        ),
    ]
