# Generated by Django 4.1.3 on 2023-06-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_api_api_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('script', models.FileField(upload_to='scripts/')),
                ('image', models.ImageField(default='path/to/default/image.jpg', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Script_Projects',
        ),
    ]
