# Generated by Django 4.1.3 on 2023-06-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_script_delete_script_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
