# Generated by Django 4.1.3 on 2023-06-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_api_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='script',
        ),
        migrations.AlterField(
            model_name='script',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
