# Generated by Django 4.1.3 on 2023-06-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_script_script_script_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='script',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
